#!/usr/bin/perl -w
###########################################
# 
# Mike Schilli, 2005 (m@perlmeister.com)
###########################################
use strict;

use File::Comments;
use Log::Log4perl qw(:easy);

Log::Log4perl->easy_init({level => $DEBUG, layout => "%F{1} %L %m%n"});

my $snoop = File::Comments->new();

my $type = $snoop->guess_type("program.a");

if($type) {
    print "Type: $type\n";
} else {
    print "Type: UNKNOWN\n";
}
